# Generated by Django 5.1.2 on 2024-11-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('categories', models.CharField(choices=[('TC', 'Tecnologia'), ('BE', 'Salao Beleza'), ('CR', 'Curiosidade'), ('GR', 'Geral')], default='GR', max_length=2)),
                ('deleted', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='posts')),
            ],
        ),
    ]
